image: maven:3-jdk-11

stages:
  - "test"

cache:
  paths:
    - .m2/repository/smartmat


test:jdk11:
  stage: test
  script:   
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  when: always

