image: maven:3-jdk-11

stages:
  - "test"

test:jdk11:
  stage: test
  script:   
    - cd smartmat 
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  when: always

