image: maven:4-jdk-17

cache:
  paths:
    - /smartmat

stages:
  - "build"
  - "test"


test:jdk17:
  stage: test
  script:    
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  when: always

